#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
ENV_FILE="${ROOT_DIR}/ci/.env.azure-provision.local"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

have_command() {
  local cmd="$1"
  command -v "${cmd}" >/dev/null 2>&1
}

validate_app_mode() {
  case "$1" in
    static-web|static-web-with-api|app-runtime) return 0 ;;
    *)
      echo "APP_MODE must be one of: static-web, static-web-with-api, app-runtime." >&2
      exit 1
      ;;
  esac
}

slugify() {
  printf '%s' "$1" |
    tr '[:upper:]' '[:lower:]' |
    sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g'
}

alnumify() {
  printf '%s' "$1" |
    tr '[:upper:]' '[:lower:]' |
    sed -E 's/[^a-z0-9]+//g'
}

truncate_chars() {
  local value="$1"
  local max_len="$2"
  printf '%s' "${value:0:${max_len}}"
}

prompt_required() {
  local var_name="$1"
  local prompt_text="$2"
  local value=""

  while [[ -z "${value}" ]]; do
    read -r -p "${prompt_text}: " value
    value="$(printf '%s' "${value}" | xargs)"
  done

  printf -v "${var_name}" '%s' "${value}"
}

prompt_default() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="$3"
  local value=""

  read -r -p "${prompt_text} [${default_value}]: " value
  value="$(printf '%s' "${value}" | xargs)"
  if [[ -z "${value}" ]]; then
    value="${default_value}"
  fi

  printf -v "${var_name}" '%s' "${value}"
}

prompt_optional() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"
  local value=""

  if [[ -n "${default_value}" ]]; then
    read -r -p "${prompt_text} [${default_value}]: " value
  else
    read -r -p "${prompt_text}: " value
  fi
  value="$(printf '%s' "${value}" | xargs)"

  if [[ -z "${value}" ]]; then
    value="${default_value}"
  fi

  printf -v "${var_name}" '%s' "${value}"
}

prompt_yes_no() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="$3"
  local value=""
  local normalized_default

  normalized_default="$(printf '%s' "${default_value}" | tr '[:upper:]' '[:lower:]')"

  while true; do
    if [[ "${normalized_default}" == "true" ]]; then
      read -r -p "${prompt_text} [Y/n]: " value
    else
      read -r -p "${prompt_text} [y/N]: " value
    fi

    value="$(printf '%s' "${value}" | tr '[:upper:]' '[:lower:]' | xargs)"
    if [[ -z "${value}" ]]; then
      value="${normalized_default}"
    elif [[ "${value}" == "y" || "${value}" == "yes" ]]; then
      value="true"
    elif [[ "${value}" == "n" || "${value}" == "no" ]]; then
      value="false"
    fi

    if [[ "${value}" == "true" || "${value}" == "false" ]]; then
      printf -v "${var_name}" '%s' "${value}"
      return 0
    fi
  done
}

detect_azure_context() {
  local account_json

  if ! have_command az; then
    return 1
  fi

  if ! account_json="$(az account show --output json 2>/dev/null)"; then
    return 1
  fi

  DETECTED_AZURE_SUBSCRIPTION_ID="$(printf '%s' "${account_json}" | sed -n 's/.*"id": "\([^"]*\)".*/\1/p' | head -n1)"
  DETECTED_AZURE_TENANT_ID="$(printf '%s' "${account_json}" | sed -n 's/.*"tenantId": "\([^"]*\)".*/\1/p' | head -n1)"

  [[ -n "${DETECTED_AZURE_SUBSCRIPTION_ID:-}" && -n "${DETECTED_AZURE_TENANT_ID:-}" ]]
}

write_env_file() {
  cat > "${ENV_FILE}" <<EOF
# Azure bootstrap template for platform/azure/provision/bootstrap-azure.sh
# Generated by platform/azure/provision/setup-azure-provision-env.sh

PROJECT_NAME=${PROJECT_NAME}
APP_MODE=${APP_MODE}
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_TENANT_ID=${AZURE_TENANT_ID}
AZURE_LOCATION=${AZURE_LOCATION}
AZURE_DNS_ZONE_NAME=${AZURE_DNS_ZONE_NAME}
AZURE_DNS_ZONE_RESOURCE_GROUP=${AZURE_DNS_ZONE_RESOURCE_GROUP}

# Optional overrides. If omitted, the bootstrap script derives them from PROJECT_NAME.
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_CONTAINER_REGISTRY=${AZURE_CONTAINER_REGISTRY}
AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
AZURE_FILE_SHARE_NAME=${AZURE_FILE_SHARE_NAME}
AZURE_CONTAINER_APPS_ENVIRONMENT=${AZURE_CONTAINER_APPS_ENVIRONMENT}
AZURE_CONTAINER_APP_NAME=${AZURE_CONTAINER_APP_NAME}
AZURE_CONTAINER_APP_STORAGE_NAME=${AZURE_CONTAINER_APP_STORAGE_NAME}
AZURE_CUSTOM_SUBDOMAIN=${AZURE_CUSTOM_SUBDOMAIN}
AZURE_POSTGRES_SERVER_NAME=${AZURE_POSTGRES_SERVER_NAME}
AZURE_POSTGRES_DATABASE_NAME=${AZURE_POSTGRES_DATABASE_NAME}
AZURE_POSTGRES_ADMIN_USERNAME=${AZURE_POSTGRES_ADMIN_USERNAME}
AZURE_POSTGRES_SKU_NAME=${AZURE_POSTGRES_SKU_NAME}
AZURE_POSTGRES_TIER=${AZURE_POSTGRES_TIER}
AZURE_POSTGRES_STORAGE_SIZE_GB=${AZURE_POSTGRES_STORAGE_SIZE_GB}
AZURE_POSTGRES_VERSION=${AZURE_POSTGRES_VERSION}

APP_NAME=${APP_NAME}
APP_ENV=${APP_ENV}
APP_RUNTIME=${APP_RUNTIME}
API_BASE_PATH=${API_BASE_PATH}
AI_ENABLED=${AI_ENABLED}
DATABASE_PROVIDER=${DATABASE_PROVIDER}
STATIC_SITE_ROOT=${STATIC_SITE_ROOT}
STATIC_API_TEMPLATE=${STATIC_API_TEMPLATE}
AZURE_CONTAINER_PORT=${AZURE_CONTAINER_PORT}
AZURE_HEALTHCHECK_PATH=${AZURE_HEALTHCHECK_PATH}

AZURE_CONTAINER_CPU=${AZURE_CONTAINER_CPU}
AZURE_CONTAINER_MEMORY=${AZURE_CONTAINER_MEMORY}
AZURE_CONTAINER_MIN_REPLICAS=${AZURE_CONTAINER_MIN_REPLICAS}
AZURE_CONTAINER_MAX_REPLICAS=${AZURE_CONTAINER_MAX_REPLICAS}
AZURE_DATA_MOUNT_PATH=${AZURE_DATA_MOUNT_PATH}
SQLITE_PATH=${SQLITE_PATH}
DOCUMENTS_PATH=${DOCUMENTS_PATH}
AUTO_RUN_MIGRATIONS=${AUTO_RUN_MIGRATIONS}
AUTO_SEED_ON_EMPTY_DB=${AUTO_SEED_ON_EMPTY_DB}

CREATE_SERVICE_PRINCIPAL=${CREATE_SERVICE_PRINCIPAL}
AZURE_SERVICE_PRINCIPAL_NAME=${AZURE_SERVICE_PRINCIPAL_NAME}
AZURE_SERVICE_PRINCIPAL_ROLE=${AZURE_SERVICE_PRINCIPAL_ROLE}
AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=${AZURE_CLI_DISABLE_CONNECTION_VERIFICATION}
POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD}

APP_BASE_URL=${APP_BASE_URL}
ADMIN_BOOTSTRAP_TOKEN=${ADMIN_BOOTSTRAP_TOKEN}
EOF
}

prompt_required PROJECT_NAME "Project name"
prompt_default APP_MODE "Application mode (static-web, static-web-with-api, or app-runtime)" "${APP_MODE:-app-runtime}"
validate_app_mode "${APP_MODE}"
PROJECT_SLUG="$(slugify "${PROJECT_NAME}")"
PROJECT_ALNUM="$(alnumify "${PROJECT_NAME}")"

if [[ -z "${PROJECT_SLUG}" || -z "${PROJECT_ALNUM}" ]]; then
  echo "Project name must contain at least one alphanumeric character." >&2
  exit 1
fi

if detect_azure_context; then
  printf 'Detected Azure context from current az session:\n'
  printf 'AZURE_SUBSCRIPTION_ID=%s\n' "${DETECTED_AZURE_SUBSCRIPTION_ID}"
  printf 'AZURE_TENANT_ID=%s\n\n' "${DETECTED_AZURE_TENANT_ID}"
  AZURE_SUBSCRIPTION_ID="${DETECTED_AZURE_SUBSCRIPTION_ID}"
  AZURE_TENANT_ID="${DETECTED_AZURE_TENANT_ID}"
else
  prompt_required AZURE_SUBSCRIPTION_ID "Azure subscription id"
  prompt_required AZURE_TENANT_ID "Azure tenant id"
fi

prompt_default AZURE_LOCATION "Azure region" "eastus2"
prompt_default AZURE_DNS_ZONE_NAME "Azure DNS zone" "example.com"
prompt_default AZURE_DNS_ZONE_RESOURCE_GROUP "Azure DNS zone resource group" "rg-shared-dns"

AZURE_RESOURCE_GROUP="rg-${PROJECT_SLUG}"
AZURE_CONTAINER_REGISTRY="$(truncate_chars "icb${PROJECT_ALNUM}acr" 50)"
AZURE_STORAGE_ACCOUNT_NAME="$(truncate_chars "icb${PROJECT_ALNUM}st" 24)"
AZURE_FILE_SHARE_NAME="$(truncate_chars "${PROJECT_SLUG}-data" 63)"
AZURE_CONTAINER_APPS_ENVIRONMENT="$(truncate_chars "${PROJECT_SLUG}-env" 32)"
AZURE_CONTAINER_APP_NAME="$(truncate_chars "${PROJECT_SLUG}-app" 32)"
AZURE_CONTAINER_APP_STORAGE_NAME="appdata"
AZURE_CUSTOM_SUBDOMAIN="${PROJECT_SLUG}"
AZURE_POSTGRES_SERVER_NAME="$(truncate_chars "icb-${PROJECT_SLUG}-pg" 63)"
AZURE_POSTGRES_DATABASE_NAME="${PROJECT_ALNUM}"
AZURE_POSTGRES_ADMIN_USERNAME="pgadmin"
AZURE_POSTGRES_SKU_NAME="Standard_B1ms"
AZURE_POSTGRES_TIER="Burstable"
AZURE_POSTGRES_STORAGE_SIZE_GB="32"
AZURE_POSTGRES_VERSION="16"

APP_NAME="${PROJECT_SLUG}"
APP_ENV="production"
APP_RUNTIME="azure-container-apps"
AI_ENABLED="false"

AZURE_CONTAINER_CPU="1"
AZURE_CONTAINER_MEMORY="2"
AZURE_CONTAINER_MIN_REPLICAS="0"
AZURE_CONTAINER_MAX_REPLICAS="1"

prompt_yes_no CREATE_SERVICE_PRINCIPAL "Create GitHub Actions service principal" "true"
AZURE_SERVICE_PRINCIPAL_NAME="${PROJECT_SLUG}-gha"
AZURE_SERVICE_PRINCIPAL_ROLE="Contributor"
prompt_yes_no AZURE_CLI_DISABLE_CONNECTION_VERIFICATION "Set AZURE_CLI_DISABLE_CONNECTION_VERIFICATION for proxy/TLS bypass" "${AZURE_CLI_DISABLE_CONNECTION_VERIFICATION:-false}"

APP_BASE_URL=""
POSTGRES_ADMIN_PASSWORD=""
ADMIN_BOOTSTRAP_TOKEN=""

if [[ "${APP_MODE}" == "static-web" ]]; then
  API_BASE_PATH="/api"
  DATABASE_PROVIDER=""
  prompt_default STATIC_SITE_ROOT "Static site root" "webapp"
  STATIC_API_TEMPLATE=""
  AZURE_CONTAINER_PORT="80"
  AZURE_HEALTHCHECK_PATH="/"
  AZURE_DATA_MOUNT_PATH=""
  SQLITE_PATH=""
  DOCUMENTS_PATH=""
  AUTO_RUN_MIGRATIONS="false"
  AUTO_SEED_ON_EMPTY_DB="false"
  AZURE_POSTGRES_SERVER_NAME=""
  AZURE_POSTGRES_DATABASE_NAME=""
  AZURE_POSTGRES_ADMIN_USERNAME=""
  AZURE_POSTGRES_SKU_NAME=""
  AZURE_POSTGRES_TIER=""
  AZURE_POSTGRES_STORAGE_SIZE_GB=""
  AZURE_POSTGRES_VERSION=""
else
  API_BASE_PATH="/api"
  DATABASE_PROVIDER="postgres"
  STATIC_SITE_ROOT="${STATIC_SITE_ROOT:-}"
  STATIC_API_TEMPLATE="${STATIC_API_TEMPLATE:-}"
  AZURE_CONTAINER_PORT="3000"
  AZURE_HEALTHCHECK_PATH="/api/health"
  AZURE_DATA_MOUNT_PATH="/mnt/app-data"
  SQLITE_PATH="/mnt/app-data/database/app.sqlite"
  DOCUMENTS_PATH="/mnt/app-data/documents"
  AUTO_RUN_MIGRATIONS="true"
  AUTO_SEED_ON_EMPTY_DB="false"

  if [[ "${APP_MODE}" == "static-web-with-api" ]]; then
    prompt_default STATIC_SITE_ROOT "Static site root" "webapp"
    prompt_required STATIC_API_TEMPLATE "Static API template name"
  else
    STATIC_SITE_ROOT=""
    STATIC_API_TEMPLATE=""
  fi
fi

prompt_optional APP_BASE_URL "App base URL override (leave blank to use https://${AZURE_CUSTOM_SUBDOMAIN}.${AZURE_DNS_ZONE_NAME})" ""
if [[ "${APP_MODE}" != "static-web" ]]; then
  prompt_optional POSTGRES_ADMIN_PASSWORD "PostgreSQL admin password override (leave blank to auto-generate on first bootstrap)" ""
  prompt_optional ADMIN_BOOTSTRAP_TOKEN "Admin bootstrap token override (leave blank to auto-generate later)" ""
fi

write_env_file

set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

printf '\nProvisioning env file updated at:\n%s\n' "${ENV_FILE}"
printf '\nDerived values:\n'
printf 'PROJECT_NAME=%s\n' "${PROJECT_NAME}"
printf 'APP_MODE=%s\n' "${APP_MODE}"
printf 'AZURE_SUBSCRIPTION_ID=%s\n' "${AZURE_SUBSCRIPTION_ID}"
printf 'AZURE_TENANT_ID=%s\n' "${AZURE_TENANT_ID}"
printf 'AZURE_RESOURCE_GROUP=%s\n' "${AZURE_RESOURCE_GROUP}"
printf 'AZURE_CONTAINER_REGISTRY=%s\n' "${AZURE_CONTAINER_REGISTRY}"
printf 'AZURE_STORAGE_ACCOUNT_NAME=%s\n' "${AZURE_STORAGE_ACCOUNT_NAME}"
printf 'AZURE_FILE_SHARE_NAME=%s\n' "${AZURE_FILE_SHARE_NAME}"
printf 'AZURE_CONTAINER_APPS_ENVIRONMENT=%s\n' "${AZURE_CONTAINER_APPS_ENVIRONMENT}"
printf 'AZURE_CONTAINER_APP_NAME=%s\n' "${AZURE_CONTAINER_APP_NAME}"
printf 'AZURE_CUSTOM_SUBDOMAIN=%s\n' "${AZURE_CUSTOM_SUBDOMAIN}"
if [[ "${APP_MODE}" != "static-web" ]]; then
  printf 'AZURE_POSTGRES_SERVER_NAME=%s\n' "${AZURE_POSTGRES_SERVER_NAME}"
  printf 'AZURE_POSTGRES_DATABASE_NAME=%s\n' "${AZURE_POSTGRES_DATABASE_NAME}"
else
  printf 'STATIC_SITE_ROOT=%s\n' "${STATIC_SITE_ROOT}"
  printf 'STATIC_API_TEMPLATE=%s\n' "${STATIC_API_TEMPLATE}"
  printf 'AZURE_CONTAINER_PORT=%s\n' "${AZURE_CONTAINER_PORT}"
  printf 'AZURE_HEALTHCHECK_PATH=%s\n' "${AZURE_HEALTHCHECK_PATH}"
fi
printf 'APP_BASE_URL=%s\n' "${APP_BASE_URL:-https://${AZURE_CUSTOM_SUBDOMAIN}.${AZURE_DNS_ZONE_NAME}}"
printf '\nCurrent shell loaded for this script run.\n'
printf 'Next step:\n'
printf 'bash platform/azure/provision/bootstrap-azure.sh\n'
